package com.apu.asc.notification;

public enum NotificationType {
  APPOINTMENT_BOOKED,
  APPOINTMENT_STATUS_CHANGED,
  APPOINTMENT_REMINDER,
  QUOTATION_READY_FOR_APPROVAL,
  QUOTATION_DECIDED,
  WORK_ORDER_ASSIGNED,
  PAYMENT_RECEIVED,
  PAYMENT_REFUNDED
}
