/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R403RouteImport } from './routes/403'
import { Route as CustomerRouteRouteImport } from './routes/customer/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManagerRouteRouteImport } from './routes/manager/route'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as StaffRouteRouteImport } from './routes/staff/route'
import { Route as TechnicianRouteRouteImport } from './routes/technician/route'
import { Route as CustomerIndexRouteImport } from './routes/customer/index'
import { Route as CustomerAppointmentsRouteImport } from './routes/customer/appointments'
import { Route as CustomerFeedbackRouteImport } from './routes/customer/feedback'
import { Route as CustomerPaymentsRouteImport } from './routes/customer/payments'
import { Route as CustomerQuotationsRouteImport } from './routes/customer/quotations'
import { Route as CustomerVehiclesRouteImport } from './routes/customer/vehicles'
import { Route as ManagerIndexRouteImport } from './routes/manager/index'
import { Route as ManagerAppointmentsRouteImport } from './routes/manager/appointments'
import { Route as ManagerAuditLogsRouteImport } from './routes/manager/audit-logs'
import { Route as ManagerOperationsRouteImport } from './routes/manager/operations'
import { Route as ManagerServicesRouteImport } from './routes/manager/services'
import { Route as ManagerVehiclesRouteImport } from './routes/manager/vehicles'
import { Route as ManagerWorkOrdersRouteImport } from './routes/manager/work-orders'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as StaffAppointmentsRouteImport } from './routes/staff/appointments'
import { Route as StaffPaymentsRouteImport } from './routes/staff/payments'
import { Route as StaffQuotationsRouteImport } from './routes/staff/quotations'
import { Route as StaffServicesRouteImport } from './routes/staff/services'
import { Route as StaffUsersRouteImport } from './routes/staff/users'
import { Route as StaffWorkOrdersRouteImport } from './routes/staff/work-orders'
import { Route as TechnicianIndexRouteImport } from './routes/technician/index'
import { Route as TechnicianFeedbackRouteImport } from './routes/technician/feedback'
import { Route as TechnicianJobsRouteImport } from './routes/technician/jobs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRouteRoute = CustomerRouteRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRouteRoute = ManagerRouteRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRouteRoute = StaffRouteRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianRouteRoute = TechnicianRouteRouteImport.update({
  id: '/technician',
  path: '/technician',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerAppointmentsRoute = CustomerAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerFeedbackRoute = CustomerFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerPaymentsRoute = CustomerPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerQuotationsRoute = CustomerQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerVehiclesRoute = CustomerVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerAppointmentsRoute = ManagerAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerAuditLogsRoute = ManagerAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerOperationsRoute = ManagerOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerServicesRoute = ManagerServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerVehiclesRoute = ManagerVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerWorkOrdersRoute = ManagerWorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffAppointmentsRoute = StaffAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffPaymentsRoute = StaffPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffQuotationsRoute = StaffQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffServicesRoute = StaffServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffUsersRoute = StaffUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffWorkOrdersRoute = StaffWorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => StaffRouteRoute,
} as any)
const TechnicianIndexRoute = TechnicianIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TechnicianRouteRoute,
} as any)
const TechnicianFeedbackRoute = TechnicianFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => TechnicianRouteRoute,
} as any)
const TechnicianJobsRoute = TechnicianJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => TechnicianRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteRouteWithChildren
  '/manager': typeof ManagerRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/technician': typeof TechnicianRouteRouteWithChildren
  '/403': typeof R403Route
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/customer/appointments': typeof CustomerAppointmentsRoute
  '/customer/feedback': typeof CustomerFeedbackRoute
  '/customer/payments': typeof CustomerPaymentsRoute
  '/customer/quotations': typeof CustomerQuotationsRoute
  '/customer/vehicles': typeof CustomerVehiclesRoute
  '/manager/appointments': typeof ManagerAppointmentsRoute
  '/manager/audit-logs': typeof ManagerAuditLogsRoute
  '/manager/operations': typeof ManagerOperationsRoute
  '/manager/services': typeof ManagerServicesRoute
  '/manager/vehicles': typeof ManagerVehiclesRoute
  '/manager/work-orders': typeof ManagerWorkOrdersRoute
  '/staff/appointments': typeof StaffAppointmentsRoute
  '/staff/payments': typeof StaffPaymentsRoute
  '/staff/quotations': typeof StaffQuotationsRoute
  '/staff/services': typeof StaffServicesRoute
  '/staff/users': typeof StaffUsersRoute
  '/staff/work-orders': typeof StaffWorkOrdersRoute
  '/technician/feedback': typeof TechnicianFeedbackRoute
  '/technician/jobs': typeof TechnicianJobsRoute
  '/customer/': typeof CustomerIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/technician/': typeof TechnicianIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/customer/appointments': typeof CustomerAppointmentsRoute
  '/customer/feedback': typeof CustomerFeedbackRoute
  '/customer/payments': typeof CustomerPaymentsRoute
  '/customer/quotations': typeof CustomerQuotationsRoute
  '/customer/vehicles': typeof CustomerVehiclesRoute
  '/manager/appointments': typeof ManagerAppointmentsRoute
  '/manager/audit-logs': typeof ManagerAuditLogsRoute
  '/manager/operations': typeof ManagerOperationsRoute
  '/manager/services': typeof ManagerServicesRoute
  '/manager/vehicles': typeof ManagerVehiclesRoute
  '/manager/work-orders': typeof ManagerWorkOrdersRoute
  '/staff/appointments': typeof StaffAppointmentsRoute
  '/staff/payments': typeof StaffPaymentsRoute
  '/staff/quotations': typeof StaffQuotationsRoute
  '/staff/services': typeof StaffServicesRoute
  '/staff/users': typeof StaffUsersRoute
  '/staff/work-orders': typeof StaffWorkOrdersRoute
  '/technician/feedback': typeof TechnicianFeedbackRoute
  '/technician/jobs': typeof TechnicianJobsRoute
  '/customer': typeof CustomerIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/staff': typeof StaffIndexRoute
  '/technician': typeof TechnicianIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteRouteWithChildren
  '/manager': typeof ManagerRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/technician': typeof TechnicianRouteRouteWithChildren
  '/403': typeof R403Route
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/customer/appointments': typeof CustomerAppointmentsRoute
  '/customer/feedback': typeof CustomerFeedbackRoute
  '/customer/payments': typeof CustomerPaymentsRoute
  '/customer/quotations': typeof CustomerQuotationsRoute
  '/customer/vehicles': typeof CustomerVehiclesRoute
  '/manager/appointments': typeof ManagerAppointmentsRoute
  '/manager/audit-logs': typeof ManagerAuditLogsRoute
  '/manager/operations': typeof ManagerOperationsRoute
  '/manager/services': typeof ManagerServicesRoute
  '/manager/vehicles': typeof ManagerVehiclesRoute
  '/manager/work-orders': typeof ManagerWorkOrdersRoute
  '/staff/appointments': typeof StaffAppointmentsRoute
  '/staff/payments': typeof StaffPaymentsRoute
  '/staff/quotations': typeof StaffQuotationsRoute
  '/staff/services': typeof StaffServicesRoute
  '/staff/users': typeof StaffUsersRoute
  '/staff/work-orders': typeof StaffWorkOrdersRoute
  '/technician/feedback': typeof TechnicianFeedbackRoute
  '/technician/jobs': typeof TechnicianJobsRoute
  '/customer/': typeof CustomerIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/technician/': typeof TechnicianIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customer'
    | '/manager'
    | '/staff'
    | '/technician'
    | '/403'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/customer/appointments'
    | '/customer/feedback'
    | '/customer/payments'
    | '/customer/quotations'
    | '/customer/vehicles'
    | '/manager/appointments'
    | '/manager/audit-logs'
    | '/manager/operations'
    | '/manager/services'
    | '/manager/vehicles'
    | '/manager/work-orders'
    | '/staff/appointments'
    | '/staff/payments'
    | '/staff/quotations'
    | '/staff/services'
    | '/staff/users'
    | '/staff/work-orders'
    | '/technician/feedback'
    | '/technician/jobs'
    | '/customer/'
    | '/manager/'
    | '/staff/'
    | '/technician/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/customer/appointments'
    | '/customer/feedback'
    | '/customer/payments'
    | '/customer/quotations'
    | '/customer/vehicles'
    | '/manager/appointments'
    | '/manager/audit-logs'
    | '/manager/operations'
    | '/manager/services'
    | '/manager/vehicles'
    | '/manager/work-orders'
    | '/staff/appointments'
    | '/staff/payments'
    | '/staff/quotations'
    | '/staff/services'
    | '/staff/users'
    | '/staff/work-orders'
    | '/technician/feedback'
    | '/technician/jobs'
    | '/customer'
    | '/manager'
    | '/staff'
    | '/technician'
  id:
    | '__root__'
    | '/'
    | '/customer'
    | '/manager'
    | '/staff'
    | '/technician'
    | '/403'
    | '/forgot-password'
    | '/invite'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/customer/appointments'
    | '/customer/feedback'
    | '/customer/payments'
    | '/customer/quotations'
    | '/customer/vehicles'
    | '/manager/appointments'
    | '/manager/audit-logs'
    | '/manager/operations'
    | '/manager/services'
    | '/manager/vehicles'
    | '/manager/work-orders'
    | '/staff/appointments'
    | '/staff/payments'
    | '/staff/quotations'
    | '/staff/services'
    | '/staff/users'
    | '/staff/work-orders'
    | '/technician/feedback'
    | '/technician/jobs'
    | '/customer/'
    | '/manager/'
    | '/staff/'
    | '/technician/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerRouteRoute: typeof CustomerRouteRouteWithChildren
  ManagerRouteRoute: typeof ManagerRouteRouteWithChildren
  StaffRouteRoute: typeof StaffRouteRouteWithChildren
  TechnicianRouteRoute: typeof TechnicianRouteRouteWithChildren
  R403Route: typeof R403Route
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician': {
      id: '/technician'
      path: '/technician'
      fullPath: '/technician'
      preLoaderRoute: typeof TechnicianRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/customer/appointments': {
      id: '/customer/appointments'
      path: '/appointments'
      fullPath: '/customer/appointments'
      preLoaderRoute: typeof CustomerAppointmentsRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/customer/feedback': {
      id: '/customer/feedback'
      path: '/feedback'
      fullPath: '/customer/feedback'
      preLoaderRoute: typeof CustomerFeedbackRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/customer/payments': {
      id: '/customer/payments'
      path: '/payments'
      fullPath: '/customer/payments'
      preLoaderRoute: typeof CustomerPaymentsRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/customer/quotations': {
      id: '/customer/quotations'
      path: '/quotations'
      fullPath: '/customer/quotations'
      preLoaderRoute: typeof CustomerQuotationsRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/customer/vehicles': {
      id: '/customer/vehicles'
      path: '/vehicles'
      fullPath: '/customer/vehicles'
      preLoaderRoute: typeof CustomerVehiclesRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/appointments': {
      id: '/manager/appointments'
      path: '/appointments'
      fullPath: '/manager/appointments'
      preLoaderRoute: typeof ManagerAppointmentsRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/audit-logs': {
      id: '/manager/audit-logs'
      path: '/audit-logs'
      fullPath: '/manager/audit-logs'
      preLoaderRoute: typeof ManagerAuditLogsRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/operations': {
      id: '/manager/operations'
      path: '/operations'
      fullPath: '/manager/operations'
      preLoaderRoute: typeof ManagerOperationsRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/services': {
      id: '/manager/services'
      path: '/services'
      fullPath: '/manager/services'
      preLoaderRoute: typeof ManagerServicesRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/vehicles': {
      id: '/manager/vehicles'
      path: '/vehicles'
      fullPath: '/manager/vehicles'
      preLoaderRoute: typeof ManagerVehiclesRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/work-orders': {
      id: '/manager/work-orders'
      path: '/work-orders'
      fullPath: '/manager/work-orders'
      preLoaderRoute: typeof ManagerWorkOrdersRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/appointments': {
      id: '/staff/appointments'
      path: '/appointments'
      fullPath: '/staff/appointments'
      preLoaderRoute: typeof StaffAppointmentsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/payments': {
      id: '/staff/payments'
      path: '/payments'
      fullPath: '/staff/payments'
      preLoaderRoute: typeof StaffPaymentsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/quotations': {
      id: '/staff/quotations'
      path: '/quotations'
      fullPath: '/staff/quotations'
      preLoaderRoute: typeof StaffQuotationsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/services': {
      id: '/staff/services'
      path: '/services'
      fullPath: '/staff/services'
      preLoaderRoute: typeof StaffServicesRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/users': {
      id: '/staff/users'
      path: '/users'
      fullPath: '/staff/users'
      preLoaderRoute: typeof StaffUsersRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/work-orders': {
      id: '/staff/work-orders'
      path: '/work-orders'
      fullPath: '/staff/work-orders'
      preLoaderRoute: typeof StaffWorkOrdersRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/technician/': {
      id: '/technician/'
      path: '/'
      fullPath: '/technician/'
      preLoaderRoute: typeof TechnicianIndexRouteImport
      parentRoute: typeof TechnicianRouteRoute
    }
    '/technician/feedback': {
      id: '/technician/feedback'
      path: '/feedback'
      fullPath: '/technician/feedback'
      preLoaderRoute: typeof TechnicianFeedbackRouteImport
      parentRoute: typeof TechnicianRouteRoute
    }
    '/technician/jobs': {
      id: '/technician/jobs'
      path: '/jobs'
      fullPath: '/technician/jobs'
      preLoaderRoute: typeof TechnicianJobsRouteImport
      parentRoute: typeof TechnicianRouteRoute
    }
  }
}

interface CustomerRouteRouteChildren {
  CustomerAppointmentsRoute: typeof CustomerAppointmentsRoute
  CustomerFeedbackRoute: typeof CustomerFeedbackRoute
  CustomerPaymentsRoute: typeof CustomerPaymentsRoute
  CustomerQuotationsRoute: typeof CustomerQuotationsRoute
  CustomerVehiclesRoute: typeof CustomerVehiclesRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
}

const CustomerRouteRouteChildren: CustomerRouteRouteChildren = {
  CustomerAppointmentsRoute: CustomerAppointmentsRoute,
  CustomerFeedbackRoute: CustomerFeedbackRoute,
  CustomerPaymentsRoute: CustomerPaymentsRoute,
  CustomerQuotationsRoute: CustomerQuotationsRoute,
  CustomerVehiclesRoute: CustomerVehiclesRoute,
  CustomerIndexRoute: CustomerIndexRoute,
}

const CustomerRouteRouteWithChildren = CustomerRouteRoute._addFileChildren(
  CustomerRouteRouteChildren,
)

interface ManagerRouteRouteChildren {
  ManagerAppointmentsRoute: typeof ManagerAppointmentsRoute
  ManagerAuditLogsRoute: typeof ManagerAuditLogsRoute
  ManagerOperationsRoute: typeof ManagerOperationsRoute
  ManagerServicesRoute: typeof ManagerServicesRoute
  ManagerVehiclesRoute: typeof ManagerVehiclesRoute
  ManagerWorkOrdersRoute: typeof ManagerWorkOrdersRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

const ManagerRouteRouteChildren: ManagerRouteRouteChildren = {
  ManagerAppointmentsRoute: ManagerAppointmentsRoute,
  ManagerAuditLogsRoute: ManagerAuditLogsRoute,
  ManagerOperationsRoute: ManagerOperationsRoute,
  ManagerServicesRoute: ManagerServicesRoute,
  ManagerVehiclesRoute: ManagerVehiclesRoute,
  ManagerWorkOrdersRoute: ManagerWorkOrdersRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}

const ManagerRouteRouteWithChildren = ManagerRouteRoute._addFileChildren(
  ManagerRouteRouteChildren,
)

interface StaffRouteRouteChildren {
  StaffAppointmentsRoute: typeof StaffAppointmentsRoute
  StaffPaymentsRoute: typeof StaffPaymentsRoute
  StaffQuotationsRoute: typeof StaffQuotationsRoute
  StaffServicesRoute: typeof StaffServicesRoute
  StaffUsersRoute: typeof StaffUsersRoute
  StaffWorkOrdersRoute: typeof StaffWorkOrdersRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteRouteChildren: StaffRouteRouteChildren = {
  StaffAppointmentsRoute: StaffAppointmentsRoute,
  StaffPaymentsRoute: StaffPaymentsRoute,
  StaffQuotationsRoute: StaffQuotationsRoute,
  StaffServicesRoute: StaffServicesRoute,
  StaffUsersRoute: StaffUsersRoute,
  StaffWorkOrdersRoute: StaffWorkOrdersRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteRouteWithChildren = StaffRouteRoute._addFileChildren(
  StaffRouteRouteChildren,
)

interface TechnicianRouteRouteChildren {
  TechnicianFeedbackRoute: typeof TechnicianFeedbackRoute
  TechnicianJobsRoute: typeof TechnicianJobsRoute
  TechnicianIndexRoute: typeof TechnicianIndexRoute
}

const TechnicianRouteRouteChildren: TechnicianRouteRouteChildren = {
  TechnicianFeedbackRoute: TechnicianFeedbackRoute,
  TechnicianJobsRoute: TechnicianJobsRoute,
  TechnicianIndexRoute: TechnicianIndexRoute,
}

const TechnicianRouteRouteWithChildren = TechnicianRouteRoute._addFileChildren(
  TechnicianRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerRouteRoute: CustomerRouteRouteWithChildren,
  ManagerRouteRoute: ManagerRouteRouteWithChildren,
  StaffRouteRoute: StaffRouteRouteWithChildren,
  TechnicianRouteRoute: TechnicianRouteRouteWithChildren,
  R403Route: R403Route,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
