@startuml
set separator none
title Appointment

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("ApuAscApplication.ApuAscApplication_boundary", "ApuAscApplication", $tags="") {
  Component(ApuAscApplication.ApuAscApplication.Appointment, "Appointment", $techn="Module", $descr="", $tags="", $link="")
  Component(ApuAscApplication.ApuAscApplication.Common, "Common", $techn="Module", $descr="", $tags="", $link="")
  Component(ApuAscApplication.ApuAscApplication.Notification, "Notification", $techn="Module", $descr="", $tags="", $link="")
  Component(ApuAscApplication.ApuAscApplication.Scheduling, "Scheduling", $techn="Module", $descr="", $tags="", $link="")
  Component(ApuAscApplication.ApuAscApplication.User, "User", $techn="Module", $descr="", $tags="", $link="")
  Component(ApuAscApplication.ApuAscApplication.Vehicle, "Vehicle", $techn="Module", $descr="", $tags="", $link="")
}

Rel(ApuAscApplication.ApuAscApplication.Appointment, ApuAscApplication.ApuAscApplication.Common, "uses", $techn="", $tags="", $link="")
Rel(ApuAscApplication.ApuAscApplication.Appointment, ApuAscApplication.ApuAscApplication.Notification, "depends on", $techn="", $tags="", $link="")
Rel(ApuAscApplication.ApuAscApplication.Appointment, ApuAscApplication.ApuAscApplication.Scheduling, "uses", $techn="", $tags="", $link="")
Rel(ApuAscApplication.ApuAscApplication.Appointment, ApuAscApplication.ApuAscApplication.User, "uses", $techn="", $tags="", $link="")
Rel(ApuAscApplication.ApuAscApplication.Appointment, ApuAscApplication.ApuAscApplication.Vehicle, "uses", $techn="", $tags="", $link="")
Rel(ApuAscApplication.ApuAscApplication.Notification, ApuAscApplication.ApuAscApplication.Common, "listens to", $techn="", $tags="", $link="")
Rel(ApuAscApplication.ApuAscApplication.Notification, ApuAscApplication.ApuAscApplication.User, "uses", $techn="", $tags="", $link="")
Rel(ApuAscApplication.ApuAscApplication.Scheduling, ApuAscApplication.ApuAscApplication.Common, "depends on", $techn="", $tags="", $link="")
Rel(ApuAscApplication.ApuAscApplication.User, ApuAscApplication.ApuAscApplication.Common, "listens to", $techn="", $tags="", $link="")
Rel(ApuAscApplication.ApuAscApplication.User, ApuAscApplication.ApuAscApplication.Common, "uses", $techn="", $tags="", $link="")
Rel(ApuAscApplication.ApuAscApplication.Vehicle, ApuAscApplication.ApuAscApplication.Common, "uses", $techn="", $tags="", $link="")
Rel(ApuAscApplication.ApuAscApplication.Vehicle, ApuAscApplication.ApuAscApplication.User, "uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml
